test
LucasDondo/TPs-Algoritmos-y-Estructuras-de-Datos pull request #1
Opened 2024-10-03 18:45 UTC by Nicolas-Mazzeo

2024-10-04 04:10 UTC, LucasDondo commented
Bueno, eso es lo que se me ocurre 🤷🏻‍♂️.
Después no sé si querrás traducir algunas cosas al inglés, o también usar `itr` y `lst` en vez de `iterador` y `lista` por la consistencia entre ambos archivos 🤷🏻.

2024-10-04 15:32 UTC, LucasDondo requested changes

2024-10-04 15:32 UTC, LucasDondo commented on tdas/lista/lista_test/lista_test.go
> +
Simplify code:
```suggestion
	require.Equal(t, 1, iterador.Borrar())
```

2024-10-04 15:32 UTC, LucasDondo commented on tdas/lista/lista_test/lista_test.go
> +	}
La segunda línea es innecesaria, pues el `BorrarPrimero` de la línea siguiente ya verifica la igualdad.
```suggestion
	for i := vol; i > 0; i-- {
		require.Equal(t, T(i), lista.BorrarPrimero())
	}
```

2024-10-04 15:32 UTC, LucasDondo commented on tdas/lista/lista_test/lista_test.go
> +	require.Equal(t, 1, lista.VerUltimo())    // El último elemento sigue siendo 3
Este comentario quedó desactualizado. Antes habían bastantes así (que no coincidía lo que decía el comentario con lo que decía el código).

2024-10-04 15:32 UTC, LucasDondo commented on tdas/lista/lista_test/lista_test.go
> +	iterador.Insertar(3) // Insertar 3 antes de 2
Bueno, acá hay varios comentarios que tampoco coinciden con el código (esa lista queda `[1, 2, 3]`, no `[3, 2, 1]`).

JAJA parece que te estoy queriendo joder, pero te juro que vine a buscar posibles cambios en el código, ¡no en los comentarios! 🤣

2024-10-04 17:17 UTC, merged

2024-10-05 15:30 UTC, Nicolas-Mazzeo commented on tdas/lista/lista_test/lista_test.go
> +	iterador.Insertar(3) // Insertar 3 antes de 2
Ahi mejore los comentarios, en este caso quedaba mejor sin tanto

2024-10-05 19:40 UTC, LucasDondo commented on tdas/lista/lista_test/lista_test.go
> +	iterador.Insertar(3) // Insertar 3 antes de 2
Seehh jajajajaja